

###
GET {{host}}/articles
Accept: application/json
Token: {{token}}

###
GET {{host}}/articles/1
Accept: application/json
Token: {{token}}

###

POST {{host}}/articles
Content-Type: application/json
Token: {{token}}

{
  "title": "this is a articles3",
  "desc": "this is a desc3",
  "content": "this is a content3",
  "coverImageUrl": "http//www.image.com/123.jpg",
  "created_by": "fym",
  "state": 1,
  "tagIds": "2,3"
}

###

PUT {{host}}/articles/1
Content-Type: application/json
Token: {{token}}

{
  "title": "this is update title",
  "state": 1
}

###

DELETE {{host}}/articles/1
Content-Type: application/json
Token: {{token}}
