

###
GET {{host}}/articles
Accept: application/json
Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfa2V5IjoiMjc1NjY4YmE2NTUwNDljZDczOWQxZDllNmIzMWNjZjEiLCJBcHBfc2VjcmV0IjoiN2M5NzI2NjMxNzBkNmJjMTg0ODRkMDViYzk4NzIyZjQiLCJleHAiOjE2MDYwNjY4OTEsImlzcyI6ImJsb2ctc2VydmljZSJ9.CTqvOMwX6sSoYtjk43aZrAKJ9bNapbIosLpWBEEo704

###
GET {{host}}/articles/2
Accept: application/json


###

POST {{host}}/articles
Content-Type: application/json

{
  "title": "this is a articles3",
  "desc": "this is a desc3",
  "content": "this is a content3",
  "coverImageUrl": "http//www.image.com/123.jpg",
  "created_by": "fym",
  "state": 1,
  "tagIds": "2,3"
}

###

PUT {{host}}/articles/1
Content-Type: application/json

{
  "title": "this is update title",
  "state": 1
}

###

DELETE {{host}}/articles/1
