GET {{common-host}}/image/c36bbd258b7ee694eb987221b2b197b0.jpg

###

# curl -X POST http://localhost:8080/upload/file -F file=@1.jpg -F type=1
POST {{common-host}}/upload/file
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="1.jpg"

< /Users/fym/Downloads/3.jpg
--WebAppBoundary
Content-Disposition: form-data; name="type"

1
--WebAppBoundary--

###

